services:
  app:
    image: node:18-alpine
    command: npm run dev
    working_dir: /app
    ports:
    - 3000:3000
    volumes:
    - .:/app
    environment:
      MONGODB_URI: mongodb://mongo/index
    depends_on:
    - mongo
  tsc:
    image: node:18-alpine
    command: npx tsc -w
    working_dir: /app
    volumes:
    - .:/app
  mongo:
    image: mongo:6.0
    volumes:
    - /data/db
