services:
  app:
    image: node:18
    command: npm run dev
    working_dir: /app
    ports:
    - 3000:3000
    volumes:
    - .:/app
    environment:
      MONGODB_URI: mongodb://mongo/mflix
    depends_on:
    - mongo
  mongo:
    image: mongo:6.0
    volumes:
    - /data/db
