apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: standard # pd-stardard
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: index
#   labels:
#     app: index
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: index
#   template:
#     metadata:
#       labels:
#         app: index
#     spec:
#       containers:
#       - name: nextjs
#         image: 
#         ports:
#         - containerPort: 80
#         volumeMounts:
#           - mountPath: "/data"
#             name: mongo-data
